"""The hand-written deep-test-manual chapters must not teach a tester to expect a leak
that the code no longer has (DRA-55).

Three tier findings were written into chapters 07/08/13 while they were real and have since
been closed in code:

* **TASK-5** — user-tier ``GET /tasks`` shipped the raw queue row, ``payload`` and ``result``
  included. ``format_task`` now projects both out (``agents/core/routers/dashboard.py``),
  pinned by ``tests/test_dashboard.py::test_tasks_user_tier_never_ships_payload_or_result``.
* ``GET /api/autonomy/tasks/{task_id}/preview`` was tier ``open`` and echoed payload-derived
  ``effects``/``target``. It is ``admin`` now.
* ``GET /api/agents/{agent_id}/soul`` was tier ``open`` and serves the gitignored personal
  overlay. It is ``user`` now.

A manual that still says "record this as still open" turns a *passing* system into a filed
bug, and — worse — teaches the tester to shrug when the leak really does come back. These
tests read the route tiers from the same snapshot the auth-matrix gate uses, so if a route is
ever un-guarded again the assertion flips to demanding the chapters warn about it.
"""

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANUAL = REPO / "docs" / "test-manual"
SNAPSHOT = REPO / "tests" / "_snapshots" / "route_auth.json"

# Hand-written chapters only. 14-api-surface-sweep.md is generated by
# scripts/gen_api_sweep.py and is corrected there, not here.
CHAPTERS = (
    "07-autonomy-governance.md",
    "08-security-privacy.md",
    "13-scenarios-and-chaos.md",
)


def _chapter(name: str) -> str:
    return (MANUAL / name).read_text(encoding="utf-8")


_STRUCK = re.compile(r"~~.*?~~", re.S)
_PAST_PAREN = re.compile(r"\((?:that |which )?(?:was|used to be)\b[^)]*\)")
_HISTORY_MARKERS = ("**FIXED", "PARTLY FIXED", "**History:**", "It used to be", "used to read")


def _present_tense_lines(text: str) -> list[str]:
    """The chapter with everything explicitly *about the past* removed.

    A corrected chapter still names the old posture — a struck-through "~~is open-tier~~"
    followed by **FIXED**, or a FAIL clause reading "(that was the old open-tier posture)".
    Naming the closed leak is the whole point of a regression case, so only what a line
    asserts in the present tense is checked. Strikethrough spans can wrap across lines, so
    they are stripped from the whole document before it is split.
    """
    stripped = _STRUCK.sub(" ", text)
    out = []
    for line in stripped.splitlines():
        out.append("" if any(m in line for m in _HISTORY_MARKERS) else _PAST_PAREN.sub("", line))
    return out


def _tier(route: str) -> str:
    tiers = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    assert route in tiers, f"{route} vanished from route_auth.json — re-anchor this test"
    return tiers[route]


def test_task5_is_fixed_in_code_not_just_on_paper() -> None:
    """The premise the doc assertions below rest on."""
    src = (REPO / "agents/core/routers/dashboard.py").read_text(encoding="utf-8")
    body = src.split("def format_task(")[1].split("\n\n")[0]
    assert 'd.pop("payload", None)' in body
    assert 'd.pop("result", None)' in body


def test_chapters_do_not_record_task5_as_still_open() -> None:
    for name in CHAPTERS:
        text = _chapter(name)
        assert "TASK-5 still open" not in text, (
            f"{name} tells the tester to file the closed TASK-5 leak as open"
        )
        assert not re.search(r"TASK-5 (payload )?leak still stands", text), name
        assert "still contains `payload` and `result`" not in text, name


def test_chapters_do_not_call_the_task_preview_route_open_tier() -> None:
    route = "GET /api/autonomy/tasks/{task_id}/preview"
    tier = _tier(route)
    if tier == "open":  # pragma: no cover — the leak came back; the manual should say so
        return
    seen = 0
    for name in CHAPTERS:
        for claim in _present_tense_lines(_chapter(name)):
            if "tasks/{task_id}/preview" not in claim and "tasks/<id>/preview" not in claim:
                continue
            assert not re.search(r"\bis \*\*open\*\*", claim), (name, claim)
            assert "tier `open`" not in claim, (name, claim)
            assert "open-tier" not in claim, (name, claim)
            seen += 1
    assert seen, "no chapter mentions the preview route any more — re-anchor this test"


def test_chapters_do_not_call_the_soul_route_open_tier() -> None:
    route = "GET /api/agents/{agent_id}/soul"
    tier = _tier(route)
    if tier == "open":  # pragma: no cover — regression; the manual should warn again
        return
    seen = 0
    for name in CHAPTERS:
        for claim in _present_tense_lines(_chapter(name)):
            if "{agent_id}/soul" not in claim and "/soul`" not in claim:
                continue
            assert not re.search(r"\bis \*\*open\*\*", claim), (name, claim)
            assert "open-tier" not in claim, (name, claim)
            assert "unauthenticated" not in claim, (name, claim)
            seen += 1
    assert seen, "no chapter mentions the soul route any more — re-anchor this test"
