"""Tests for the encrypted-at-rest SecretStore (H12.1)."""
import sys
from pathlib import Path

import pytest

repo_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(repo_root))
sys.path.insert(0, str(repo_root / "agents"))

from agents.core.secrets import SecretStore, SecretStoreError, _HAS_CRYPTOGRAPHY


def test_set_get_roundtrip(tmp_path):
    store = SecretStore(tmp_path / "s.enc", key="hunter2-passphrase")
    store.set("ANTHROPIC_API_KEY", "sk-abc-123")
    assert store.get("ANTHROPIC_API_KEY") == "sk-abc-123"


def test_value_not_plaintext_on_disk(tmp_path):
    path = tmp_path / "s.enc"
    store = SecretStore(path, key="some-passphrase")
    store.set("TOKEN", "super-secret-value")
    raw = path.read_bytes()
    assert b"super-secret-value" not in raw


def test_get_missing_returns_default(tmp_path):
    store = SecretStore(tmp_path / "s.enc", key="k")
    assert store.get("nope") is None
    assert store.get("nope", "fallback") == "fallback"


def test_delete(tmp_path):
    store = SecretStore(tmp_path / "s.enc", key="k")
    store.set("a", "1")
    # Keep the mutating delete() out of the assert expression so it isn't
    # stripped under `python -O` (CodeQL py/side-effect-in-assert).
    deleted = store.delete("a")
    assert deleted is True
    assert store.get("a") is None
    deleted_again = store.delete("a")
    assert deleted_again is False


def test_contains_and_names(tmp_path):
    store = SecretStore(tmp_path / "s.enc", key="k")
    store.set("b", "2")
    store.set("a", "1")
    assert "a" in store
    assert "z" not in store
    assert store.names() == ["a", "b"]


def test_persists_across_instances(tmp_path):
    path = tmp_path / "s.enc"
    SecretStore(path, key="shared-pass").set("X", "value-x")
    reopened = SecretStore(path, key="shared-pass")
    assert reopened.get("X") == "value-x"


def test_wrong_key_fails_to_decrypt(tmp_path):
    path = tmp_path / "s.enc"
    SecretStore(path, key="right-key").set("X", "secret")
    # Different passphrase derives a different key → tamper/decrypt error.
    bad = SecretStore(path, key="wrong-key")
    with pytest.raises(SecretStoreError):
        bad.get("X")


def test_autogenerated_key_zero_config(tmp_path):
    # No env key and no explicit key → a 0600 keyfile is generated and reused.
    path = tmp_path / "s.enc"
    store = SecretStore(path)
    store.set("K", "v")
    keyfile = path.with_suffix(path.suffix + ".key")
    assert keyfile.exists()
    # Reopen with no key → same generated keyfile → decrypts.
    assert SecretStore(path).get("K") == "v"


def test_raw_fernet_key_accepted(tmp_path):
    if not _HAS_CRYPTOGRAPHY:
        pytest.skip("cryptography not installed")
    from cryptography.fernet import Fernet
    raw = Fernet.generate_key().decode("ascii")
    store = SecretStore(tmp_path / "s.enc", key=raw)
    store.set("K", "v")
    assert store.get("K") == "v"


def test_migrate_plaintext_skips_existing(tmp_path):
    store = SecretStore(tmp_path / "s.enc", key="k")
    store.set("EXISTING", "old")
    n = store.migrate_plaintext({"EXISTING": "new", "FRESH": "fresh-val", "NONE": None})
    assert n == 1  # only FRESH written; EXISTING skipped, None skipped
    assert store.get("EXISTING") == "old"
    assert store.get("FRESH") == "fresh-val"


def test_migrate_plaintext_overwrite(tmp_path):
    store = SecretStore(tmp_path / "s.enc", key="k")
    store.set("E", "old")
    n = store.migrate_plaintext({"E": "new"}, overwrite=True)
    assert n == 1
    assert store.get("E") == "new"


def test_backend_label(tmp_path):
    store = SecretStore(tmp_path / "s.enc", key="k")
    assert store.backend in ("fernet", "hmac-fallback")


def test_unicode_secret(tmp_path):
    store = SecretStore(tmp_path / "s.enc", key="k")
    store.set("ro", "parolă-cu-diacritice-ăîâ")
    assert store.get("ro") == "parolă-cu-diacritice-ăîâ"


def test_pure_python_fallback_roundtrip(tmp_path):
    # Exercise the fallback cipher directly regardless of cryptography presence.
    store = SecretStore(tmp_path / "s.enc", key="k")
    token = store._fallback_encrypt(b"hello fallback")
    assert token.startswith("xhmac1:")
    assert "hello fallback" not in token
    assert store._fallback_decrypt(token.encode("ascii")) == "hello fallback"


def test_fallback_tamper_detected(tmp_path):
    store = SecretStore(tmp_path / "s.enc", key="k")
    token = store._fallback_encrypt(b"data")
    # Flip a char in the base64 body → HMAC tag mismatch.
    body = list(token)
    body[-1] = "A" if body[-1] != "A" else "B"
    with pytest.raises(SecretStoreError):
        store._fallback_decrypt("".join(body).encode("ascii"))
