"""M2.3 / AUD-16 OpenAPI-to-TypeScript typegen gate."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


def test_generated_openapi_types_are_committed():
    schema = ROOT / "frontend" / "src" / "api" / "schema.gen.ts"
    text = schema.read_text(encoding="utf-8")

    assert "auto-generated by openapi-typescript" in text
    assert "export interface paths" in text
    assert '"/status"' in text


def test_frontend_typegen_script_is_pinned_to_live_openapi():
    package = json.loads((ROOT / "frontend" / "package.json").read_text(encoding="utf-8"))
    script = package["scripts"]["typegen:openapi"]

    assert "openapi-typescript@7.13.0" in script
    assert "http://127.0.0.1:8765/openapi.json" in script
    assert "src/api/schema.gen.ts" in script


def test_ci_fails_when_generated_openapi_types_drift():
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")

    assert "openapi-types:" in workflow
    assert "npm run typegen:openapi" in workflow
    assert "git diff --exit-code -- frontend/src/api/schema.gen.ts" in workflow
