"""scripts/doctor.py — the install check-up: every check reports a named reason.

Hermetic: a fake urllib opener stands in for /readyz and the runtime probes, a temp
root stands in for the checkout, and the smoke is a fake runner. No network, no server.
"""

import hashlib
import io
import json
import sys
import urllib.error
from pathlib import Path

import pytest

repo_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(repo_root))
sys.path.insert(0, str(repo_root / "agents"))

from scripts import bootstrap, doctor  # noqa: E402


def _write_lock_pair(root: Path, name: str, *, stale: bool = False) -> None:
    src = root / f"{name}.txt"
    src.write_text(f"{name}-dep==1\n", encoding="utf-8")
    digest = hashlib.sha256(src.read_bytes()).hexdigest()
    if stale:
        digest = "0" * 64
    (root / f"{name}.lock").write_text(
        f"# AUTOGENERATED\n# source-sha256: {digest}\n{name}-dep==1 --hash=sha256:x\n",
        encoding="utf-8",
    )


@pytest.fixture()
def healthy_root(tmp_path, monkeypatch):
    for name in ("requirements", "requirements-beta", "requirements-dev"):
        _write_lock_pair(tmp_path, name)
    venv_py = bootstrap.venv_python(tmp_path)
    venv_py.parent.mkdir(parents=True)
    venv_py.write_text("#!/bin/sh\n", encoding="utf-8")
    monkeypatch.setenv("JARVIS_HOME", str(tmp_path / "data"))
    monkeypatch.delenv("JARVIS_HOST", raising=False)
    monkeypatch.delenv("JARVIS_USER_TOKEN", raising=False)
    monkeypatch.delenv("JARVIS_ADMIN_TOKEN", raising=False)
    return tmp_path


class _Resp:
    def __init__(self, status=200, body=b'{"status":"ready"}'):
        self.status = status
        self._body = body

    def read(self):
        return self._body

    def close(self):
        pass


def _opener(*, readyz=200, ollama=True):
    def open_(url, timeout=None):
        if url.endswith("/readyz"):
            if readyz is None:
                raise urllib.error.URLError(ConnectionRefusedError(111, "refused"))
            if readyz != 200:
                raise urllib.error.HTTPError(url, readyz, "not ready", {}, None)
            return _Resp(200)
        if "11434" in url and ollama:
            return _Resp(200, b"{}")
        raise urllib.error.URLError(ConnectionRefusedError(111, "refused"))
    return open_


# ── the healthy install ────────────────────────────────────────────
def test_healthy_install_is_green_and_exits_zero(healthy_root, capsys):
    report = doctor.run_doctor(healthy_root, opener=_opener(), version_info=(3, 12, 0, "final", 0))
    by = report.by_name()
    assert report.ok is True
    assert by["python"].reason == "python_ok:3.12"
    assert by["venv"].reason == "venv_ok"
    assert by["locks_in_sync"].reason == "locks_ok"
    assert by["bind_is_loopback"].reason == "loopback"
    assert by["data_root_writable"].reason == "writable"
    assert by["data_root_writable"].detail == str(healthy_root / "data")
    assert by["runtimes"].reason == "found:ollama"
    assert by["readyz"].reason == "ready"
    assert by["smoke"].status == doctor.SKIP and by["smoke"].reason == "skipped"
    assert [c.name for c in report.checks] == list(doctor.REQUIRED) + list(doctor.ADVISORY)


# ── each check names its reason ────────────────────────────────────
def test_python_floor_reason():
    check = doctor.check_python((3, 11, 2, "final", 0))
    assert (check.status, check.reason) == (doctor.FAIL, "python_too_old:3.11<3.12")


def test_venv_missing_reason(tmp_path):
    check = doctor.check_venv(tmp_path)
    assert (check.status, check.reason) == (doctor.FAIL, "venv_missing")


def test_lock_stale_and_missing_reasons(tmp_path):
    _write_lock_pair(tmp_path, "requirements")
    _write_lock_pair(tmp_path, "requirements-beta", stale=True)
    (tmp_path / "requirements-dev.txt").write_text("pytest\n", encoding="utf-8")  # no lock
    rows = {src: reason for src, _lock, reason in doctor.lock_status(tmp_path)}
    assert rows == {
        "requirements.txt": "ok",
        "requirements-beta.txt": "lock_stale",
        "requirements-dev.txt": "lock_missing",
    }
    check = doctor.check_locks(tmp_path)
    assert check.status == doctor.FAIL
    assert check.reason == "lock_stale:requirements-beta.lock"
    assert "lock_missing:requirements-dev.lock" in check.detail


def test_repo_locks_are_in_sync_by_the_same_rule_as_lock_deps_sh():
    """The doctor's rule is scripts/lock_deps.sh --check re-derived in Python; the real
    repo must pass it (otherwise CI's lockfile guard would already be red)."""
    assert doctor.check_locks(repo_root).reason == "locks_ok"


@pytest.mark.parametrize("env, status, reason", [
    ({}, doctor.OK, "loopback"),
    ({"JARVIS_HOST": "localhost"}, doctor.OK, "loopback"),
    ({"JARVIS_HOST": "::1"}, doctor.OK, "loopback"),
    ({"JARVIS_HOST": "0.0.0.0"}, doctor.FAIL, "non_loopback_without_token"),
    ({"JARVIS_HOST": "192.168.1.20"}, doctor.FAIL, "non_loopback_without_token"),
    ({"JARVIS_HOST": "0.0.0.0", "JARVIS_USER_TOKEN": "abc"}, doctor.OK, "non_loopback_with_token"),
    ({"JARVIS_HOST": "0.0.0.0", "JARVIS_ADMIN_TOKEN": "abc"}, doctor.OK, "non_loopback_with_token"),
])
def test_bind_check_mirrors_assert_safe_bind(env, status, reason):
    check = doctor.check_bind(env)
    assert (check.status, check.reason) == (status, reason)


def test_loopback_set_cannot_drift_from_boot_guards():
    from agents.core import boot_guards
    assert frozenset(boot_guards._LOOPBACK_HOSTS) == doctor.LOOPBACK_HOSTS


def test_data_root_not_writable_reason(tmp_path, monkeypatch):
    blocker = tmp_path / "file-not-dir"
    blocker.write_text("x", encoding="utf-8")
    env = {"JARVIS_HOME": str(blocker / "memory")}
    monkeypatch.setenv("JARVIS_HOME", env["JARVIS_HOME"])
    check = doctor.check_data_root(tmp_path, env)
    assert check.status == doctor.FAIL
    assert check.reason == "data_root_not_writable"
    assert str(blocker / "memory") in check.detail


def test_data_root_falls_back_to_env_precedence_when_paths_is_unimportable(tmp_path, monkeypatch):
    import builtins
    real_import = builtins.__import__

    def broken(name, *a, **k):
        if name == "agents.core.paths":
            raise ImportError("broken install")
        return real_import(name, *a, **k)

    monkeypatch.setattr(builtins, "__import__", broken)
    assert doctor.resolve_data_root(tmp_path, {}) == tmp_path / "memory_logs"
    assert doctor.resolve_data_root(tmp_path, {"JARVIS_MEMORY_DIR": "/x/y"}) == Path("/x/y")


def test_runtimes_check_is_advisory_with_named_detail():
    check = doctor.check_runtimes(_opener(ollama=False))
    assert check.status == doctor.WARN
    assert check.reason == "no_local_runtime"
    assert check.detail == "ollama=connection_refused;lm_studio=connection_refused"


def test_readyz_reasons():
    assert doctor.check_readyz(_opener(readyz=None)).reason == "server_not_running"
    not_ready = doctor.check_readyz(_opener(readyz=503))
    assert (not_ready.status, not_ready.reason) == (doctor.WARN, "readyz_status:503")
    assert doctor.check_readyz(_opener(readyz=200)).status == doctor.OK


def test_smoke_runs_only_on_request_and_names_failures(healthy_root):
    class Proc:
        def __init__(self, rc, out="", err=""):
            self.returncode, self.stdout, self.stderr = rc, out, err

    calls = []

    def ok_run(argv, **kw):
        calls.append(argv)
        return Proc(0, json.dumps({"ok": True, "agents": 12}))

    def bad_run(argv, **kw):
        return Proc(1, "", "Install smoke failed: /readyz returned 503\n")

    skipped = doctor.check_smoke(healthy_root, enabled=False, run=ok_run)
    assert skipped.status == doctor.SKIP and calls == []

    good = doctor.check_smoke(healthy_root, enabled=True, run=ok_run)
    assert (good.status, good.reason, good.detail) == (doctor.OK, "ok", "12 agents")
    assert calls[0][0] == str(bootstrap.venv_python(healthy_root))
    assert calls[0][1].endswith("install_smoke.py")

    bad = doctor.check_smoke(healthy_root, enabled=True, run=bad_run)
    assert (bad.status, bad.reason) == (doctor.WARN, "smoke_failed")
    assert "503" in bad.detail


# ── verdict / exit code ────────────────────────────────────────────
def test_advisory_failures_do_not_fail_the_run(healthy_root):
    report = doctor.run_doctor(healthy_root, opener=_opener(readyz=None, ollama=False),
                               version_info=(3, 12, 0, "final", 0))
    assert report.ok is True
    statuses = {c.name: c.status for c in report.checks}
    assert statuses["runtimes"] == doctor.WARN and statuses["readyz"] == doctor.WARN


def test_required_failure_fails_the_run_and_the_cli(healthy_root, monkeypatch, capsys):
    monkeypatch.setenv("JARVIS_HOST", "0.0.0.0")
    report = doctor.run_doctor(healthy_root, opener=_opener(), version_info=(3, 12, 0, "final", 0))
    assert report.ok is False
    assert report.by_name()["bind_is_loopback"].status == doctor.FAIL

    monkeypatch.setattr(doctor, "run_doctor",
                        lambda root, **kw: report)
    assert doctor.main(["--root", str(healthy_root), "--json"]) == 1
    payload = json.loads(capsys.readouterr().out)
    assert payload["ok"] is False
    names = {c["name"]: c for c in payload["checks"]}
    assert names["bind_is_loopback"]["reason"] == "non_loopback_without_token"

    text = doctor.format_report(report)
    assert "[FAIL] bind_is_loopback" in text
    assert "NOT healthy" in text


def test_cli_exit_zero_when_healthy(healthy_root, monkeypatch, capsys):
    report = doctor.run_doctor(healthy_root, opener=_opener(), version_info=(3, 12, 0, "final", 0))
    monkeypatch.setattr(doctor, "run_doctor", lambda root, **kw: report)
    assert doctor.main(["--root", str(healthy_root)]) == 0
    out = capsys.readouterr().out
    assert "verdict: healthy" in out
    assert "[skip] smoke" in out


def test_doctor_is_stdlib_only_apart_from_bootstrap():
    import ast
    src = (repo_root / "scripts" / "doctor.py").read_text(encoding="utf-8")
    names = set()
    for node in ast.walk(ast.parse(src)):
        if isinstance(node, ast.Import):
            names.update(a.name.split(".")[0] for a in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            names.add(node.module.split(".")[0])
    # `agents` is imported lazily inside a try/except (broken-install fallback) — the
    # only non-stdlib names at module level are `scripts` (bootstrap) and `agents`.
    assert names - set(sys.stdlib_module_names) <= {"scripts", "agents"}


def test_report_serialises(healthy_root):
    report = doctor.run_doctor(healthy_root, opener=_opener(), version_info=(3, 12, 0, "final", 0))
    payload = report.to_dict()
    json.dumps(payload)
    assert set(payload) == {"ok", "root", "checks"}
    assert all(set(c) == {"name", "status", "reason", "detail"} for c in payload["checks"])
    buf = io.StringIO()
    print(doctor.format_report(report), file=buf)
    assert "Nerva doctor" in buf.getvalue()
