#!/usr/bin/env bash
# Cabinet v0.1.0 — Pure Python installer
# DISABLED until core modules are complete.
# This script will bootstrap the cabinet on Bonobo WS + Pi 5.

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║     Cabinet v0.1.0 — Pure Python Stack Install  ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "⚠️  Installer not yet active — core Python modules are still WIP."
echo ""
echo "What this script will do when ready:"
echo ""
echo "  PHASE 1: Bonobo WS (Pop!_OS)"
echo "  ──────────────────────────────"
echo "  1. Install system deps: python3.12, pip, docker, ollama"
echo "  2. python3 -m venv .venv && source .venv/bin/activate"
echo "  3. pip install -r requirements.txt"
echo "  4. ollama pull deepseek-r1:32b-q4_K_M"
echo "  5. ollama pull qwen2.5:14b"
echo "  6. ollama pull qwen2.5:7b"
echo "  7. python -m core.orchestrator --init"
echo ""
echo "  PHASE 2: Pi 5 (always-on services)"
echo "  ──────────────────────────────"
echo "  8. docker compose up -d qdrant neo4j n8n homebridge"
echo "  9. Configure Pi as heartbeat relay"
echo "  10. Verify connectivity Bonobo <-> Pi"
echo ""
echo "  PHASE 3: Voice Stack"
echo "  ──────────────────────────────"
echo "  11. Install openWakeWord + custom training"
echo "  12. Install faster-whisper large-v3 (GPU)"
echo "  13. Install Kokoro 82M ONNX TTS"
echo "  14. Test voice pipeline: wake -> STT -> route -> TTS"
echo ""
echo "  PHASE 4: Agents"
echo "  ──────────────────────────────"
echo "  15. python -m core.orchestrator --load-all"
echo "  16. Enable heartbeats"
echo "  17. Test each agent individually"
echo "  18. Test multi-agent orchestration"
echo ""
echo "For now: manually install Ollama and pull models."
echo "Then paste any SOUL.md as system prompt in Open WebUI"
echo "to test agent personas."
echo ""
exit 0
