// Public bookmark IDs are explicit literals. Never derive them from function names at runtime.
export const CONSOLE_PANELS = [
  {"id": "command-center", "label": "Command Center", "group": "Start", "component": "CommandCenterPanel"},
  {"id": "today-receipt", "label": "Today Receipt", "group": "Start", "component": "TodayReceiptPanel"},
  {"id": "model-setup", "label": "Model Setup", "group": "Start", "component": "ModelSetupPanel"},
  {"id": "docs", "label": "Documentation", "group": "Start", "component": "DocsPanel"},
  {"id": "presence-inbox", "label": "Presence Inbox", "group": "Home", "component": "PresenceInboxPanel"},
  {"id": "ambient-watch", "label": "Ambient Watch", "group": "Home", "component": "AmbientWatchPanel"},
  {"id": "house", "label": "House", "group": "Home", "component": "HousePanel"},
  {"id": "camera", "label": "Camera", "group": "Home", "component": "CameraPanel"},
  {"id": "data-spaces", "label": "Data Spaces", "group": "Memory", "component": "DataSpacesPanel"},
  {"id": "local-docs", "label": "Local Docs", "group": "Memory", "component": "LocalDocsPanel"},
  {"id": "notes", "label": "Notes", "group": "Memory", "component": "NotesPanel"},
  {"id": "note-docs", "label": "Note Docs", "group": "Memory", "component": "NoteDocsPanel"},
  {"id": "vault", "label": "Vault", "group": "Memory", "component": "VaultPanel"},
  {"id": "kg", "label": "Kg", "group": "Memory", "component": "KgPanel"},
  {"id": "memory-write", "label": "Memory Write", "group": "Memory", "component": "MemoryWritePanel"},
  {"id": "long-term-memory", "label": "Long-Term Memory", "group": "Memory", "component": "LongTermMemoryPanel"},
  {"id": "memory-hygiene", "label": "Memory Hygiene", "group": "Memory", "component": "MemoryHygienePanel"},
  {"id": "memory-consolidate", "label": "Memory Consolidate", "group": "Memory", "component": "MemoryConsolidatePanel"},
  {"id": "memory-eval", "label": "Memory Eval", "group": "Memory", "component": "MemoryEvalPanel"},
  {"id": "capture", "label": "Capture", "group": "Memory", "component": "CapturePanel"},
  {"id": "reflection", "label": "Reflection", "group": "Memory", "component": "ReflectionPanel"},
  {"id": "provenance", "label": "Provenance", "group": "Memory", "component": "ProvenancePanel"},
  {"id": "security-skills-map", "label": "Security Skills Map", "group": "Trust", "component": "SecuritySkillsMapPanel"},
  {"id": "payments", "label": "Payments", "group": "Trust", "component": "PaymentsPanel"},
  {"id": "signal-governance", "label": "Signal Governance", "group": "Trust", "component": "SignalGovernancePanel"},
  {"id": "trust-ops", "label": "Trust Ops", "group": "Trust", "component": "TrustOpsPanel"},
  {"id": "kill-switch", "label": "Kill Switch", "group": "Trust", "component": "KillSwitchPanel"},
  {"id": "kernel-metrics", "label": "Kernel Metrics", "group": "Trust", "component": "KernelMetricsPanel"},
  {"id": "readiness", "label": "Readiness", "group": "Trust", "component": "ReadinessPanel"},
  {"id": "loop-breaker", "label": "Loop Breaker", "group": "Trust", "component": "LoopBreakerPanel"},
  {"id": "governance", "label": "Governance", "group": "Trust", "component": "GovernancePanel"},
  {"id": "posture", "label": "Posture", "group": "Trust", "component": "PosturePanel"},
  {"id": "audit-anchors", "label": "Audit Anchors", "group": "Trust", "component": "AuditAnchorsPanel"},
  {"id": "security-skills", "label": "Security Skills", "group": "Trust", "component": "SecuritySkillsPanel"},
  {"id": "skill-switches", "label": "Skill Switches", "group": "Trust", "component": "SkillSwitchesPanel"},
  {"id": "network-monitor", "label": "Network Monitor", "group": "Trust", "component": "NetworkMonitorPanel"},
  {"id": "comms-rate", "label": "Comms Rate", "group": "Trust", "component": "CommsRatePanel"},
  {"id": "safe-comms-draft", "label": "Safe Comms Draft", "group": "Trust", "component": "SafeCommsDraftPanel"},
  {"id": "secrets", "label": "Secrets", "group": "Trust", "component": "SecretsPanel"},
  {"id": "capabilities", "label": "Capabilities", "group": "Trust", "component": "CapabilitiesPanel"},
  {"id": "pairing", "label": "Pairing", "group": "Trust", "component": "PairingPanel"},
  {"id": "injection-scan", "label": "Injection Scan", "group": "Trust", "component": "InjectionScanPanel"},
  {"id": "permissions", "label": "Permissions", "group": "Trust", "component": "PermissionsPanel"},
  {"id": "osint", "label": "Osint", "group": "Interop", "component": "OsintPanel"},
  {"id": "marketplace-admin", "label": "Marketplace Admin", "group": "Interop", "component": "MarketplaceAdminPanel"},
  {"id": "skills-import", "label": "Skills Import", "group": "Interop", "component": "SkillsImportPanel"},
  {"id": "writeback-digest", "label": "Writeback Digest", "group": "Interop", "component": "WritebackDigestPanel"},
  {"id": "webhooks", "label": "Webhooks", "group": "Interop", "component": "WebhooksPanel"},
  {"id": "a2-a-inbox", "label": "A2 A Inbox", "group": "Interop", "component": "A2AInboxPanel"},
  {"id": "mesh-peers", "label": "Mesh Peers", "group": "Interop", "component": "MeshPeersPanel"},
  {"id": "satellites", "label": "Satellites", "group": "Interop", "component": "SatellitesPanel"},
  {"id": "oracle", "label": "Oracle", "group": "Interop", "component": "OraclePanel"},
  {"id": "marketplace", "label": "Marketplace", "group": "Interop", "component": "MarketplacePanel"},
  {"id": "skill-history", "label": "Skill History", "group": "Interop", "component": "SkillHistoryPanel"},
  {"id": "packs", "label": "Packs", "group": "Interop", "component": "PacksPanel"},
  {"id": "signal-routing", "label": "Signal Routing", "group": "Interop", "component": "SignalRoutingPanel"},
  {"id": "watchlist", "label": "Watchlist", "group": "Interop", "component": "WatchlistPanel"},
  {"id": "onboarding", "label": "Onboarding", "group": "Observe", "component": "OnboardingPanel"},
  {"id": "code-intel", "label": "Code Intel", "group": "Observe", "component": "CodeIntelPanel"},
  {"id": "coach", "label": "Coach", "group": "Observe", "component": "CoachPanel"},
  {"id": "review-quality", "label": "Review Quality", "group": "Observe", "component": "ReviewQualityPanel"},
  {"id": "agents-arena", "label": "Agents Arena", "group": "Observe", "component": "AgentsArenaPanel"},
  {"id": "eval", "label": "Eval", "group": "Observe", "component": "EvalPanel"},
  {"id": "review", "label": "Review", "group": "Observe", "component": "ReviewPanel"},
  {"id": "arena", "label": "Arena", "group": "Observe", "component": "ArenaPanel"},
  {"id": "quality", "label": "Quality", "group": "Observe", "component": "QualityPanel"},
  {"id": "apm", "label": "APM", "group": "Observe", "component": "APMPanel"},
  {"id": "logs", "label": "Logs", "group": "Observe", "component": "LogsPanel"},
  {"id": "model-info", "label": "Model Info", "group": "Observe", "component": "ModelInfoPanel"},
  {"id": "design-manifest", "label": "Design Manifest", "group": "Observe", "component": "DesignManifestPanel"},
  {"id": "feedback", "label": "Feedback", "group": "Observe", "component": "FeedbackPanel"},
  {"id": "self-improvement", "label": "Self Improvement", "group": "Observe", "component": "SelfImprovementPanel"},
  {"id": "pending-skills", "label": "Pending Skills", "group": "Observe", "component": "PendingSkillsPanel"},
  {"id": "cognition", "label": "Cognition", "group": "Observe", "component": "CognitionPanel"},
  {"id": "swarm", "label": "Swarm", "group": "Observe", "component": "SwarmPanel"},
  {"id": "sub-agents", "label": "Sub Agents", "group": "Observe", "component": "SubAgentsPanel"},
  {"id": "system-map", "label": "System Map", "group": "Observe", "component": "SystemMapPanel"},
  {"id": "host-readiness", "label": "Host Readiness", "group": "Build", "component": "HostReadinessPanel"},
  {"id": "images", "label": "Images", "group": "Build", "component": "ImagesPanel"},
  {"id": "creative", "label": "Creative", "group": "Build", "component": "CreativePanel"},
  {"id": "desktop-allowlist", "label": "Desktop Allowlist", "group": "Build", "component": "DesktopAllowlistPanel"},
  {"id": "workflow-traces", "label": "Workflow Traces", "group": "Build", "component": "WorkflowTracesPanel"},
  {"id": "workflows", "label": "Workflows", "group": "Build", "component": "WorkflowsPanel"},
  {"id": "workflow-builder", "label": "Workflow Builder", "group": "Build", "component": "WorkflowBuilderPanel"},
  {"id": "sandbox", "label": "Sandbox", "group": "Build", "component": "SandboxPanel"},
  {"id": "templates", "label": "Templates", "group": "Build", "component": "TemplatesPanel"},
  {"id": "acquisition", "label": "Acquisition", "group": "Build", "component": "AcquisitionPanel"},
  {"id": "media-director", "label": "Media Director", "group": "Build", "component": "MediaDirectorPanel"},
  {"id": "media-gallery", "label": "Media Gallery", "group": "Build", "component": "MediaGalleryPanel"},
  {"id": "publish-readiness", "label": "Publish Readiness", "group": "Build", "component": "PublishReadinessPanel"},
  {"id": "operator", "label": "Operator", "group": "Build", "component": "OperatorPanel"},
  {"id": "screen-reflex", "label": "Screen Reflex", "group": "Build", "component": "ScreenReflexPanel"},
  {"id": "company-room", "label": "Company Room", "group": "Autonomy & Agents", "component": "CompanyRoomPanel"},
  {"id": "quickbar", "label": "Quickbar", "group": "Autonomy & Agents", "component": "QuickbarPanel"},
  {"id": "autonomy-control", "label": "Autonomy Control", "group": "Autonomy & Agents", "component": "AutonomyControlPanel"},
  {"id": "mission-canvas", "label": "Mission Canvas", "group": "Autonomy & Agents", "component": "MissionCanvasPanel"},
  {"id": "decision-inbox", "label": "Decision Inbox", "group": "Autonomy & Agents", "component": "DecisionInboxPanel"},
  {"id": "missions", "label": "Missions", "group": "Autonomy & Agents", "component": "MissionsPanel"},
  {"id": "agent-autonomy", "label": "Agent Autonomy", "group": "Autonomy & Agents", "component": "AgentAutonomyPanel"},
  {"id": "today", "label": "Today", "group": "Autonomy & Agents", "component": "TodayPanel"},
  {"id": "schedule", "label": "Schedule", "group": "Autonomy & Agents", "component": "SchedulePanel"},
  {"id": "jobs", "label": "Jobs", "group": "Autonomy & Agents", "component": "JobsPanel"},
  {"id": "learning", "label": "Learning", "group": "Autonomy & Agents", "component": "LearningPanel"},
  {"id": "sessions", "label": "Sessions", "group": "Autonomy & Agents", "component": "SessionsPanel"},
  {"id": "heartbeat", "label": "Heartbeat", "group": "Autonomy & Agents", "component": "HeartbeatPanel"},
  {"id": "transcript", "label": "Transcript", "group": "Autonomy & Agents", "component": "TranscriptPanel"},
  {"id": "escalation", "label": "Escalation", "group": "Autonomy & Agents", "component": "EscalationPanel"},
  {"id": "llm-routing", "label": "Llm Routing", "group": "Admin", "component": "LlmRoutingPanel"},
  {"id": "support-voice", "label": "Support Voice", "group": "Admin", "component": "SupportVoicePanel"},
  {"id": "backup", "label": "Backup", "group": "Admin", "component": "BackupPanel"},
  {"id": "o-auth", "label": "O Auth", "group": "Admin", "component": "OAuthPanel"},
  {"id": "settings", "label": "Settings", "group": "Admin", "component": "SettingsPanel"},
  {"id": "prompts", "label": "Prompts", "group": "Admin", "component": "PromptsPanel"},
  {"id": "rooms", "label": "Rooms", "group": "Admin", "component": "RoomsPanel"},
  {"id": "lm-studio", "label": "LM Studio", "group": "Admin", "component": "LMStudioPanel"},
  {"id": "vlm-describe", "label": "Vlm Describe", "group": "Admin", "component": "VlmDescribePanel"},
  {"id": "auth-profiles", "label": "Auth Profiles", "group": "Admin", "component": "AuthProfilesPanel"},
  {"id": "provider-check", "label": "Provider Check", "group": "Admin", "component": "ProviderCheckPanel"},
  {"id": "provider-quota", "label": "Provider Quota", "group": "Admin", "component": "ProviderQuotaPanel"},
  {"id": "inspector", "label": "Inspector", "group": "Admin", "component": "InspectorPanel"},
  {"id": "system-profile", "label": "System Profile", "group": "Admin", "component": "SystemProfilePanel"},
] as const;
