#!/usr/bin/env bash
# AUD-10 (F33): regenerate the hash-pinned lockfiles from the requirements*.txt
# sources. Each lock is resolved for Python 3.12 (the CI + runtime target) and
# --universal, so a single file serves both the ubuntu and windows CI matrices.
# Installs are then enforced with `pip install --require-hashes -r <lock>`, which
# aborts if any downloaded artifact's hash does not match — defeating a tampered
# index, a typosquat, or a compromised release slipping in transitively.
#
# Usage:
#   ./scripts/lock_deps.sh           regenerate every lock in place (needs uv)
#   ./scripts/lock_deps.sh --check   fail if any lock is stale for its source
#                                     .txt — the CI drift guard (lockfile.yml).
#                                     Deterministic: compares the source sha256
#                                     embedded in the lock, so an unrelated
#                                     upstream release never reds an unrelated PR
#                                     (version refreshes are thirdparty-autoupdate's
#                                     job, not this guard's). No uv/network needed.
#
# uv resolves for a *target* Python version regardless of the interpreter running
# it, so numpy 2.5.0 (which needs Python >=3.12) locks correctly even from an
# older local interpreter. https://docs.astral.sh/uv/
set -euo pipefail

PY=3.12
cd "$(dirname "$0")/.."

SOURCES=(requirements.txt requirements-beta.txt requirements-dev.txt)
lock_for() { echo "${1%.txt}.lock"; }
src_sha()  { sha256sum "$1" | cut -d' ' -f1; }

compile() {
  local src=$1 out=$2 tmp
  command -v uv >/dev/null 2>&1 || {
    echo "error: uv is required to regenerate locks — https://docs.astral.sh/uv/" >&2
    exit 1
  }
  tmp=$(mktemp)
  uv pip compile "$src" \
    --generate-hashes --universal --python-version "$PY" \
    --no-header --quiet -o "$tmp"
  {
    printf '# AUTOGENERATED by scripts/lock_deps.sh from %s — do not edit by hand.\n' "$src"
    printf '# Regenerate after editing %s:  ./scripts/lock_deps.sh\n' "$src"
    printf '# source-sha256: %s\n' "$(src_sha "$src")"
    cat "$tmp"
  } >"$out"
  rm -f "$tmp"
}

if [[ "${1:-}" == "--check" ]]; then
  rc=0
  for src in "${SOURCES[@]}"; do
    out=$(lock_for "$src")
    if [[ ! -f "$out" ]]; then
      echo "::error file=$out::lockfile $out is missing — run ./scripts/lock_deps.sh"
      rc=1; continue
    fi
    want=$(src_sha "$src")
    have=$(sed -n 's/^# source-sha256: //p' "$out" | head -1)
    if [[ "$want" != "$have" ]]; then
      echo "::error file=$out::$out is stale for $src — run ./scripts/lock_deps.sh and commit the result."
      rc=1
    fi
  done
  [[ $rc -eq 0 ]] && echo "All locks are in sync with their requirements*.txt sources."
  exit $rc
fi

for src in "${SOURCES[@]}"; do
  out=$(lock_for "$src")
  echo "compiling $src -> $out"
  compile "$src" "$out"
done
echo "Done. Review the diff, then commit the updated *.lock files."
